/**
 * Data Injection Script for Browserbase Email Automation
 * 
 * This script contains the actual data from your CSV files.
 * Copy and paste this BEFORE running the main automation script.
 */

// Extract domains from CSV (first 100 for testing - you can expand this)
const DOMAINS_DATA = [
    'https://www.sanrio.com',
    'https://www.khy.com',
    'https://skims.com',
    'https://www.forever21.com',
    'https://soldejaneiro.com',
    'https://www.naturemade.com',
    'https://www.laurageller.com',
    'https://thursdayboots.com',
    'https://jeffreestarcosmetics.com',
    'https://www.aquariumcoop.com',
    'https://fromourplace.com',
    'https://www.thehydrojug.com',
    'https://www.thesill.com',
    'https://www.blackanddecker.com',
    'https://petalandpup.com',
    'https://www.trueclassictees.com',
    'https://miketyson.com',
    'https://frankiesbikinis.com',
    'https://www.getcasely.com',
    'https://www.glowrecipe.com',
    'https://fentybeauty.com',
    'https://www.maryruthorganics.com',
    'https://www.gorjana.com',
    'https://thrivecausemetics.com',
    'https://www.alphapaw.com',
    'https://atari.com',
    'https://liquiddeath.com',
    'https://showmeyourmumu.com',
    'https://www.revlon.com',
    'https://www.americangirl.com',
    'https://www.igloocoolers.com',
    'https://www.celestron.com',
    'https://jessicasimpson.com',
    'https://www.luxyhair.com',
    'https://www.tenthousandvillages.com',
    'https://www.rhodeskin.com',
    'https://theblacktux.com',
    'https://fahertybrand.com',
    'https://www.fast-growing-trees.com',
    'https://www.colorescience.com',
    'https://www.unique-vintage.com',
    'https://cozyearth.com',
    'https://mythical.com',
    'https://riflepaperco.com',
    'https://www.toddsnyder.com',
    'https://1stphorm.com',
    'https://fellowproducts.com',
    'https://saiehello.com',
    'https://www.keenfootwear.com',
    'https://www.homage.com'
];

// Extract emails from CSV
const EMAILS_DATA = [
    'rohan.seth@openripplestudio.info',
    'rohan.s@openripplestudio.info',
    'rohan.seth@trygetripplemedia.com',
    'rohan.s@trygetripplemedia.com',
    'rohan.seth@trygetripplestudio.com',
    'rohan.s@trygetripplestudio.com',
    'rohan.seth@gogetrippleonline.com',
    'rohan.s@gogetrippleonline.com',
    'rohan.seth@meetgetrippledigital.com',
    'rohan.s@meetgetrippledigital.com',
    'rohan.seth@meetgetripplelabs.com',
    'rohan.s@meetgetripplelabs.com',
    'rohan.seth@thegetrippleagency.com',
    'rohan.s@thegetrippleagency.com',
    'rohan.seth@thegetripplestudio.com',
    'rohan.s@thegetripplestudio.com',
    'rohan.seth@trygetripplehq.com',
    'rohan.s@trygetripplehq.com',
    'rohan.seth@opengetripplemedia.com',
    'rohan.s@opengetripplemedia.com',
    'rohan.seth@opengetripplestudio.com',
    'rohan.s@opengetripplestudio.com',
    'previews@ripplepreviews.com',
    'rohan.seth@getrippleaihq.com',
    'rohan.s@getrippleaihq.com',
    'rohan.seth@myrippleaiads.com',
    'rohan.s@myrippleaiads.com',
    'rohan.seth@openrippleailabs.com',
    'rohan.s@openrippleailabs.com',
    'rohan.seth@therippleaihub.com',
    'rohan.s@therippleaihub.com',
    'rohan.seth@tryrippleaihub.com',
    'rohan.s@tryrippleaihub.com',
    'rohan.seth@userippleaidigital.com',
    'rohan.s@userippleaidigital.com',
    'rohan.seth@gorippleaihq.com',
    'rohan.s@gorippleaihq.com',
    'rohan.seth@meetrippleaiagency.com',
    'rohan.s@meetrippleaiagency.com',
    'rohan.seth@rippleaistudio.com',
    'rohan.s@rippleaistudio.com',
    'rohan.seth@getrippleaiagency.com',
    'rohan.s@getrippleaiagency.com',
    'rohan.seth@meetrippleaimedia.com',
    'rohan.s@meetrippleaimedia.com',
    'rohan.seth@myrippleaihub.com',
    'rohan.s@myrippleaihub.com',
    'rohan.seth@rippleaihq.com',
    'rohan.s@rippleaihq.com',
    'rohan.seth@therippleaiagency.com',
    'rohan.s@therippleaiagency.com',
    'rohan.seth@userippleaisolutions.com',
    'rohan.s@userippleaisolutions.com',
    'rohan.seth@myrippleai.com',
    'rohan.s@myrippleai.com',
    'rohan.seth@rippleaimedia.com',
    'rohan.s@rippleaimedia.com',
    'rohan.seth@therippleaiads.com',
    'rohan.s@therippleaiads.com',
    'rohan.seth@tryrippleaionline.com',
    'rohan.s@tryrippleaionline.com',
    'rohan.seth@tryrippleaisolutions.com',
    'rohan.s@tryrippleaisolutions.com',
    'rseth@openripplestudio.info',
    'rohan.seth.2@openripplestudio.info',
    'r.seth@openripplestudio.info',
    'r.s.m@openripplestudio.info',
    'rohan@openripplestudio.info'
];

// Make data globally available
window.AUTOMATION_DOMAINS = DOMAINS_DATA;
window.AUTOMATION_EMAILS = EMAILS_DATA;

console.log(`📊 Data loaded: ${DOMAINS_DATA.length} domains, ${EMAILS_DATA.length} emails`);
console.log('✅ Ready to run automation!') 