name: Sync BigQuery to Supabase

on:
  # Run daily at 6 AM UTC (2 AM EST)
  schedule:
    - cron: '0 6 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      limit:
        description: 'Limit number of records to sync (leave empty for all)'
        required: false
        type: string
      sync_storeleads:
        description: 'Sync storeleads data'
        required: false
        type: boolean
        default: true

env:
  PYTHON_VERSION: '3.11'

jobs:
  sync-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up BigQuery credentials
      run: |
        echo '${{ secrets.BIGQUERY_CREDENTIALS }}' > bigquery_credentials.json
    
    - name: Verify sync script exists
      run: |
        if [ ! -f "sync_bigquery_to_supabase.py" ]; then
          echo "❌ Sync script not found in root directory"
          find . -name "sync_bigquery_to_supabase.py" -type f
          exit 1
        else
          echo "✅ Sync script found: sync_bigquery_to_supabase.py"
        fi
    
    - name: Run BigQuery to Supabase sync
      env:
        GOOGLE_APPLICATION_CREDENTIALS: bigquery_credentials.json
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        PYTHONUNBUFFERED: "1"
      run: |
        echo "🚀 Starting BigQuery to Supabase sync..."
        echo "🔧 Python version: $(python --version)"
        python -u sync_bigquery_to_supabase.py
    
    - name: Clean up credentials
      if: always()
      run: |
        rm -f bigquery_credentials.json
    
    - name: Summary
      if: success()
      run: |
        echo "✅ Sync job completed successfully!"
        echo "📊 Email campaign data synced from BigQuery to Supabase"
        echo "🔍 Check Supabase dashboard for updated data"
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Sync job failed! Check the logs for details."
        # You can add Slack/Discord/email notifications here if needed
    
    - name: Notify on success
      if: success()
      run: |
        echo "✅ Sync job completed successfully!"
        # You can add success notifications here if needed 