name: Sync BigQuery to Supabase

on:
  # Run daily at 6 AM UTC (2 AM EST)
  schedule:
    - cron: '0 6 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      limit:
        description: 'Limit number of records to sync (leave empty for all)'
        required: false
        type: string
      sync_storeleads:
        description: 'Sync storeleads data'
        required: false
        type: boolean
        default: true

jobs:
  sync-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('email_analytics/data/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary  # PostgreSQL adapter
        pip install -r email_analytics/data/requirements.txt
    
    - name: Set up Google Cloud credentials
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "$GCP_SERVICE_ACCOUNT_KEY" > /tmp/gcp-service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-service-account.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-service-account.json" >> $GITHUB_ENV
    
    - name: Run BigQuery to Supabase sync
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-service-account.json
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        echo "🚀 Starting BigQuery to Supabase sync..."
        python sync_bigquery_to_supabase.py
    
    - name: Clean up credentials
      if: always()
      run: |
        rm -f /tmp/gcp-service-account.json
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Sync job failed! Check the logs for details."
        # You can add Slack/Discord/email notifications here if needed
    
    - name: Notify on success
      if: success()
      run: |
        echo "✅ Sync job completed successfully!"
        # You can add success notifications here if needed 